spring:
  application:
    name: helpdesk-server

  datasource:
    url: jdbc:postgresql://localhost:17777/helper
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8888
